"""autogenerated by genpy from messages/set_headlights.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class set_headlights(genpy.Message):
  _md5sum = "49d66d76cc979659a5a84fa6781b6bee"
  _type = "messages/set_headlights"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 left_red
int16 left_green
int16 left_blue
int16 right_red
int16 right_green
int16 right_blue

"""
  __slots__ = ['left_red','left_green','left_blue','right_red','right_green','right_blue']
  _slot_types = ['int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_red,left_green,left_blue,right_red,right_green,right_blue

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(set_headlights, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_red is None:
        self.left_red = 0
      if self.left_green is None:
        self.left_green = 0
      if self.left_blue is None:
        self.left_blue = 0
      if self.right_red is None:
        self.right_red = 0
      if self.right_green is None:
        self.right_green = 0
      if self.right_blue is None:
        self.right_blue = 0
    else:
      self.left_red = 0
      self.left_green = 0
      self.left_blue = 0
      self.right_red = 0
      self.right_green = 0
      self.right_blue = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6h.pack(_x.left_red, _x.left_green, _x.left_blue, _x.right_red, _x.right_green, _x.right_blue))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.left_red, _x.left_green, _x.left_blue, _x.right_red, _x.right_green, _x.right_blue,) = _struct_6h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6h.pack(_x.left_red, _x.left_green, _x.left_blue, _x.right_red, _x.right_green, _x.right_blue))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.left_red, _x.left_green, _x.left_blue, _x.right_red, _x.right_green, _x.right_blue,) = _struct_6h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6h = struct.Struct("<6h")
