"""autogenerated by genpy from messages/sonar_distance.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class sonar_distance(genpy.Message):
  _md5sum = "0a19756bf9bdac6019c0fd00f6c542ae"
  _type = "messages/sonar_distance"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Gives a timestamp so nodes make sure they use current readings
time stamp

# Position of the sonar (0-23), where 0 is right
int8 pos

# Distance reading from the front sonar in mm
uint16 distance0
# Distance reading from the back sonar in mm
uint16 distance1

"""
  __slots__ = ['stamp','pos','distance0','distance1']
  _slot_types = ['time','int8','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,pos,distance0,distance1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sonar_distance, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.pos is None:
        self.pos = 0
      if self.distance0 is None:
        self.distance0 = 0
      if self.distance1 is None:
        self.distance1 = 0
    else:
      self.stamp = genpy.Time()
      self.pos = 0
      self.distance0 = 0
      self.distance1 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2Ib2H.pack(_x.stamp.secs, _x.stamp.nsecs, _x.pos, _x.distance0, _x.distance1))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.stamp.secs, _x.stamp.nsecs, _x.pos, _x.distance0, _x.distance1,) = _struct_2Ib2H.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2Ib2H.pack(_x.stamp.secs, _x.stamp.nsecs, _x.pos, _x.distance0, _x.distance1))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.stamp.secs, _x.stamp.nsecs, _x.pos, _x.distance0, _x.distance1,) = _struct_2Ib2H.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2Ib2H = struct.Struct("<2Ib2H")
