/**
 ******************************************************************************
 * WARNING: THIS IS AN AUTOGENERATED FILE!
 *
 * Editing this file is USELESS. It will be overwritten during the build.
 * To properly edit this file, edit its corresponding *.template.* file, which
 * a script run by CMake uses to generate this file.
 *
 * This file was generated via rules in src/generate_behavior_lists.py.
 *
 * Please see that file for a description of syntax and procedure for
 * creating auto-generated files.
 *
 * THIS WARNING IS LONG TO MAKE SURE IT GETS YOUR ATTENTION!
 * THANK YOU.
 *****************************************************************************
 */

#include "BehaviorList.h"

BehaviorList::BehaviorList()
{
  behavior_list.push_back(behavior<pause_scout>);
  behavior_list.push_back(behavior<danger_marking>);
  behavior_list.push_back(behavior<draw_ccw_circle>);
  behavior_list.push_back(behavior<draw_cw_circle>);
  behavior_list.push_back(behavior<line_follow>);
  behavior_list.push_back(behavior<maze_solve>);
  behavior_list.push_back(behavior<maze_solve_simple>);
  behavior_list.push_back(behavior<navigationMap>);
  behavior_list.push_back(behavior<Odometry>);
  behavior_list.push_back(behavior<Odometry_new>);
  behavior_list.push_back(behavior<Scheduler>);
  behavior_list.push_back(behavior<smart_runaround>);
  behavior_list.push_back(behavior<WH_Robot>);
  behavior_list.push_back(behavior<wl_test>);
  return;
}

BehaviorList::~BehaviorList()
{
  while(!behavior_list.empty())
    behavior_list.pop_back();
}
